#!/bin/bash

# Setup secondary network device
/sbin/ip address add 192.168.10.1/24 dev enp2s0
/sbin/ip link set dev enp2s0 up

# Setup DHCP server
/usr/bin/dnsmasq --conf-file=/etc/dnsmasq.conf --conf-dir=/etc/dnsmasq.d

sleep infinity
